name: 'Standard Responsive Images'
description: 'Provides basic responsive images and accompanying image styles.'
type: 'Media'
install:
  - image
  - responsive_image
config:
  import:
    image: '*'
